#+OPTIONS: p:t
#+TITLE: Linus Diary

* Diary information
** TODOs
All todos will left at the diary entry where the point came up.
After this they will be marked as DONE and the time of closing will be put under the item.


* Meetings
** Meeting [2022-02-09 ons]
Came up with project idea.

** Meeting [2022-02-18 fre]
*** DONE Fix the Trello structure
CLOSED: [2022-02-18 fre 14:31]
*** DONE Fix the README (needs slight updating still, but a baseline has been established)
CLOSED: [2022-02-18 fre 17:32]
*** DONE Start exporting the diary to make it more easily readable
CLOSED: [2022-02-18 fre 14:29]

** Writing [2022-02-22 tue]
I've written a blog post about making Gloss library work on Windows. This was a huge roadblock
but after this we should be able to get it to work on all of our devices.

https://linusblog.netlify.app/haskell_gloss_wsl/

** Individual work [2022-02-28 mon]
Done some slight work on the CLI for the program.

** Individual work [2022-03-02 wed]
I have been very sick for the past week, and work has been slow from my part.
I have been working on the CLI for the program and will begin work on merging everything afterwards.

*** 15:25
CLI input has been made better. Choices have been implemented, and answers can be received.
Next step, handle the answers we receive.

*** 15:29
Scrapping the idea to save avatars to a file, unless we have a bunch of extra time at the end.

*** 15:50
Setup webhooks for GitHub and our Discord server, for fun.

** Individual work [2022-3-4 Fri] 
*** DONE Standardise the generator functions so that the input is the offset rather than the position that they need to be on.
CLOSED: [2022-3-4 Fri 10:36] 

*** DONE Create fringe function for hair (and fix hairstyles)
CLOSED: [2022-3-4 Fri 10:52] 

*** DONE Implement randomness to positioning.
CLOSED: [2022-3-7 Mon 09:52] 

*** DONE Write test cases, not really sure how
CLOSED: [2022-3-7 Mon 10:13] 

** Final work [2022-3-7 Mon]
Integrating everything and updating documentation. 
This in order to create the final version to upload as a release.

Refactored program to make imports explicit + changed some slight code formatting.

Updating tests for generator functions and getting ready to push final version.

Pushing final version, v1.0.